In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "../data/raw/Sambhajinagar_UHI_Dataset_V1.csv"
)

df.head()

,system:index,LST,Latitude,Longitude,NDBI,NDVI,.geo
0,0,43.919170,19.970832,75.438700,0.127207,0.162286,"{""type"":""Point"",""coordinates"":[75.438699969521..."
1,1,39.060455,19.729093,75.209548,-0.272423,0.570751,"{""type"":""Point"",""coordinates"":[75.209547657446..."
2,2,40.231127,19.788775,75.225639,0.055877,0.099371,"{""type"":""Point"",""coordinates"":[75.225638822972..."
3,3,44.884761,19.960297,75.544582,0.121404,0.196037,"{""type"":""Point"",""coordinates"":[75.544582071463..."
4,4,48.502735,19.867709,75.486062,0.133151,0.165262,"{""type"":""Point"",""coordinates"":[75.486061551196..."

In [3]:
df.columns

Index(['system:index', 'LST', 'Latitude', 'Longitude', 'NDBI', 'NDVI', '.geo'], dtype='str')

In [4]:
df = df.drop(
    columns=[".geo", "system:index"]
)

df.head()

         LST   Latitude  Longitude      NDBI      NDVI
0  43.919170  19.970832  75.438700  0.127207  0.162286
1  39.060455  19.729093  75.209548 -0.272423  0.570751
2  40.231127  19.788775  75.225639  0.055877  0.099371
3  44.884761  19.960297  75.544582  0.121404  0.196037
4  48.502735  19.867709  75.486062  0.133151  0.165262

In [5]:
df.isnull().sum()

LST          0
Latitude     0
Longitude    0
NDBI         0
NDVI         0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop_duplicates()

df.shape

(5000, 5)

In [8]:
df.head()

         LST   Latitude  Longitude      NDBI      NDVI
0  43.919170  19.970832  75.438700  0.127207  0.162286
1  39.060455  19.729093  75.209548 -0.272423  0.570751
2  40.231127  19.788775  75.225639  0.055877  0.099371
3  44.884761  19.960297  75.544582  0.121404  0.196037
4  48.502735  19.867709  75.486062  0.133151  0.165262

In [9]:
df.to_csv(
    "../data/processed/cleaned_uhi.csv",
    index=False
)

print("Cleaned Dataset Saved")

Cleaned Dataset Saved