In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    "../data/processed/cleaned_uhi.csv"
)

df.head()

         LST   Latitude  Longitude      NDBI      NDVI
0  43.919170  19.970832  75.438700  0.127207  0.162286
1  39.060455  19.729093  75.209548 -0.272423  0.570751
2  40.231127  19.788775  75.225639  0.055877  0.099371
3  44.884761  19.960297  75.544582  0.121404  0.196037
4  48.502735  19.867709  75.486062  0.133151  0.165262

In [4]:
df["Green_Built_Ratio"] = (
    df["NDVI"] /
    (abs(df["NDBI"]) + 0.01)
)

df.head()

         LST   Latitude  Longitude      NDBI      NDVI  Green_Built_Ratio
0  43.919170  19.970832  75.438700  0.127207  0.162286           1.182783
1  39.060455  19.729093  75.209548 -0.272423  0.570751           2.020910
2  40.231127  19.788775  75.225639  0.055877  0.099371           1.508423
3  44.884761  19.960297  75.544582  0.121404  0.196037           1.491866
4  48.502735  19.867709  75.486062  0.133151  0.165262           1.154459

In [5]:
df["Heat_Exposure_Index"] = (
    df["NDBI"] *
    df["LST"]
)

df.head()

,LST,Latitude,Longitude,NDBI,NDVI,Green_Built_Ratio,Heat_Exposure_Index
0,43.919170,19.970832,75.438700,0.127207,0.162286,1.182783,5.586821
1,39.060455,19.729093,75.209548,-0.272423,0.570751,2.020910,-10.640952
2,40.231127,19.788775,75.225639,0.055877,0.099371,1.508423,2.248012
3,44.884761,19.960297,75.544582,0.121404,0.196037,1.491866,5.449194
4,48.502735,19.867709,75.486062,0.133151,0.165262,1.154459,6.458205

In [6]:
df.describe()

,LST,Latitude,Longitude,NDBI,NDVI,Green_Built_Ratio,Heat_Exposure_Index
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,43.389135,19.889075,75.357174,0.028941,0.240790,4.014722,1.470197
std,3.346183,0.085450,0.119309,0.099037,0.117976,4.315923,4.197115
min,27.762190,19.724079,75.142142,-0.383288,-0.128937,-9.282245,-14.143441
25%,41.162965,19.817358,75.254562,-0.023969,0.159963,1.490942,-0.974186
50%,43.563696,19.889976,75.355773,0.052578,0.211080,2.472158,2.303169
75%,45.946056,19.960294,75.456165,0.099394,0.296487,4.579304,4.493739
max,51.435396,20.042755,75.585577,0.401310,0.751738,46.586742,17.654711

In [7]:
df.to_csv(
    "../data/processed/featured_uhi.csv",
    index=False
)

print("Feature Engineering Complete")

Feature Engineering Complete